version: "3"
services:
    mariadb:
      image: mariadb:latest
      container_name: mariadb
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=pass
        - MYSQL_USER=tamago
        - MYSQL_PASSWORD=hogehoge
        - MYSQL_DATABASE=hoge
networks:
  esnet:
